# Generated by Django 5.1.4 on 2025-08-13 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='Представление агента сессии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Сессия активна')),
                ('unique_key', models.CharField(max_length=36, unique=True, verbose_name='Уникальный код')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Владелец сессии')),
            ],
            options={
                'verbose_name': 'Сессия пользователя',
                'verbose_name_plural': 'Сессии пользователей',
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['-created_at', '-id'], name='ix_user_session_cr_id')],
            },
        ),
    ]
