services:
  web-app:
    build:
      context: ..
      dockerfile: ./deploy/docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../project:/app
    environment:
      - DB_HOST=db
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=password

    depends_on:
      - db

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
