services:
  web-app:
    build:
      context: ..
      dockerfile: ./deploy/docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=password
    depends_on: 
      db:
        condition: service_healthy
    volumes:
      - ../project:/app

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d dbname"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
